var neurons = [
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 1},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{state: false, act: 0.5, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
];
