var neurons = [
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
{act: 1, con: [{weight: Math.random(), index: 0}, {weight: Math.random(), index: 1}, {weight: Math.random(), index: 2}, {weight: Math.random(), index: 3}, {weight: Math.random(), index: 4}, {weight: Math.random(), index: 5}, {weight: Math.random(), index: 6}, {weight: Math.random(), index: 7}, {weight: Math.random(), index: 8}, {weight: Math.random(), index: 9}]},
];
